datadump.location:
      author: "C:/Users/kamalakannan.k/Downloads/test-authors.txt"
      works: "C:/Users/kamalakannan.k/Downloads/test-works.txt"
spring:
   main:
     allow-circular-references: true 
#### generate token in Cassendra and put client Id, password and Token in respective places.
   cassandra:
      keyspace-name: main
      username:  client Id
      password:  password
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s


### Download secure bundle in your cassandra DB and add it to the resources
datastax.astra:
    secure-connect-bundle: secure-connect-betterreads.zip


astra.db:
    id: put DataBase Id
    region: us-east1
    keyspace: main
    application.token: token

